# Imports

In [5]:
import pandas as pd

In [6]:
player_boxscores = pd.read_csv("data/player_boxscores.csv")

In [ ]:
def get_joining_dates_for_player(player_id: int):
    # GET TEAMS WHERE THE PLAYER PLAYED
    teams_where_player_played = player_boxscores[player_boxscores["player_id"] == player_id][["team_id", "team_abbreviation", "team_name"]].drop_duplicates()

    for idx, team in teams_where_player_played.iterrows():
        # PLAYER NAME AND ID
        teams_where_player_played.loc[idx, "player_id"] = player_id
        teams_where_player_played.loc[idx, "player_name"] = player_boxscores[
            (player_boxscores["player_id"] == player_id) &
            (player_boxscores["team_abbreviation"] == team["team_abbreviation"])
        ]["player_name"].iloc[0]

        # JOINING DATE
        date_of_joining = player_boxscores[
            (player_boxscores["player_id"] == player_id) &
            (player_boxscores["team_abbreviation"] == team["team_abbreviation"])
        ]["game_date"].min()
        teams_where_player_played.loc[idx, "date_of_joining"] = date_of_joining

        # EXIT DATE
        date_of_exit = player_boxscores[
            (player_boxscores["player_id"] == player_id) &
            (player_boxscores["team_abbreviation"] == team["team_abbreviation"])
        ]["game_date"].max()
        teams_where_player_played.loc[idx, "date_of_exit"] = date_of_exit

    return teams_where_player_played

def get_joining_dates_for_players(players_id: list[int]):
    res_df = pd.DataFrame()
    for id in players_id:
        res_df = pd.concat([res_df, get_joining_dates_for_player(id)])

    return res_df

In [8]:
# Usage
lebron_id = player_boxscores[player_boxscores["player_name"] == "LeBron James"]["player_id"].iloc[0]
shaquille_id = player_boxscores[player_boxscores["player_name"] == "Shaquille O'Neal"]["player_id"].iloc[0]

print(f"LeBron James ID: {lebron_id}")
print(f"Shaquille O'Neal ID: {shaquille_id}")

display(get_joining_dates_for_player(lebron_id))
display(get_joining_dates_for_players([lebron_id, shaquille_id]))

LeBron James ID: 2544
Shaquille O'Neal ID: 406

,team_id,team_abbreviation,team_name,player_id,player_name,date_of_joining,date_of_exit
132,1610612747,LAL,Los Angeles Lakers,2544.0,LeBron James,2018-10-18T00:00:00,2026-05-11T00:00:00
217594,1610612739,CLE,Cleveland Cavaliers,2544.0,LeBron James,2003-10-29T00:00:00,2018-06-08T00:00:00
328916,1610612748,MIA,Miami Heat,2544.0,LeBron James,2010-10-26T00:00:00,2014-06-15T00:00:00

,team_id,team_abbreviation,team_name,player_id,player_name,date_of_joining,date_of_exit
132,1610612747,LAL,Los Angeles Lakers,2544.0,LeBron James,2018-10-18T00:00:00,2026-05-11T00:00:00
217594,1610612739,CLE,Cleveland Cavaliers,2544.0,LeBron James,2003-10-29T00:00:00,2018-06-08T00:00:00
328916,1610612748,MIA,Miami Heat,2544.0,LeBron James,2010-10-26T00:00:00,2014-06-15T00:00:00
406952,1610612738,BOS,Boston Celtics,406.0,Shaquille O'Neal,2010-10-26T00:00:00,2011-05-09T00:00:00
433636,1610612739,CLE,Cleveland Cavaliers,406.0,Shaquille O'Neal,2009-10-27T00:00:00,2010-05-13T00:00:00
461577,1610612756,PHX,Phoenix Suns,406.0,Shaquille O'Neal,2008-02-20T00:00:00,2009-04-15T00:00:00
500536,1610612748,MIA,Miami Heat,406.0,Shaquille O'Neal,2004-11-03T00:00:00,2008-01-21T00:00:00
592647,1610612747,LAL,Los Angeles Lakers,406.0,Shaquille O'Neal,1996-11-01T00:00:00,2004-06-15T00:00:00